version: '3.4'
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
# docker-compose run --rm zerocodegenerator cg /cg-mysql-schema.sql cg_master_resource
services:
  api:
    image: crud_sandbox_api_1  # temp name only for schema.sql
    container_name: crud_sandbox_api_1
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        SCHEMA_SQL: ./cg-mysql-schema.sql
        #SCHEMA_DESC: cg_master_resource
        SCHEMA_DESC: ./one.crud.json
        MODULE_NAME: cg
    # ports: # or nginx
    #  - 8080:8080
    volumes:
      - ./api/config/application-dev.yml:/webapps/config/application-dev.yml
    depends_on:
        - mysqlserver
     
  web:
    image: crud_sandbox_web_1  # temp name only for schema.sql
    container_name: crud_sandbox_web_1
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        ENTRY_SCRIPT: ./web/entrypoint.sh
            ## below for schema
        SCHEMA_SQL: ./cg-mysql-schema.sql
        TABLE_NAME: cg_master_resource
    volumes: 
      - ./web/config/global.js:/usr/src/web/src/global.js
      - ./web/config/config.js:/usr/src/web/public/config.js
    #for node-gateway below
      - ./out/web/src/pages:/usr/src/web/src/pages
    ports:
      - 8000:8000
    command:
        - npm
        - start
    depends_on: 
      - api
      - nodegateway

  nodegateway:
    #/usr/src/gateway/src/assets/json/masterResource/config/masterResource-setting.json
    image: zelejs/nodegateway:latest
    container_name: nodegateway
    environment:
      NODE_ENV: production
    volumes: 
      - ./out/web/src/pages:/usr/src/gateway/src/assets/json
          #for development env
      # - ./node-gateway/src/src:/usr/src/gateway/src

  mysqlserver:
    image: daocloud.io/library/mysql:5.7
    # container_name: mysqlserver
    privileged: true
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
    volumes:
        - ./api/mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
      # - crud_sandbox_data:/var/lib/mysql

  nginx:
      container_name: crud_sandbox_api_gw
      privileged: true
      image: 'daocloud.io/library/nginx:latest'
      ports:
        - 8080:80  # 8080 for another app
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
      depends_on:
        - web

  busybox:
    # image: daocloud.io/library/busybox
    image: yauritux/busybox-curl
    container_name: busybox

networks:
  default:
    name: crud_sandbox_network

volumes: 
  crud_sandbox_data:    
