version: '3.4'
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
# docker-compose run --rm zerocodegenerator cg /cg-mysql-schema.sql cg_master_resource
services:
  api:
    image: crud_sandbox_api_1  # temp name only for schema.sql
    container_name: crud_sandbox_api_1
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        SCHEMA_SQL: ./cg-mysql-schema.sql
        #SCHEMA_DESC: cg_master_resource  #table name or /path/to/cruds.json
        SCHEMA_DESC: ./onemany.crud.json
        MODULE_NAME: cg
    ports: # or nginx
      - 8080:8080
    volumes:
      - ./api/config/application-dev.yml:/webapps/config/application-dev.yml
    depends_on:
        - mysqlserver
  mysqlserver:
     image: daocloud.io/library/mysql:5.7
     container_name: mysqlserver
     privileged: true
     environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
     volumes:
        - ./api/mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
      # - ./api/data:/var/lib/mysql
  busybox:
    # image: daocloud.io/library/busybox
    image: yauritux/busybox-curl
    container_name: busybox

networks:
  default: 
    name: crud_sandbox_network
