version: '3.4'
# docker build --memory=2g -t nodegateway:latest .
services:
  nodegateway:
    image: zelejs/nodegateway:latest
    build:
      context: .
      dockerfile: ./Dockerfile.src
  # for src debug
    #volumes: 
    #  - ./src:/usr/share