FROM zelejs/zerocodegenerator:latest as gencode
ARG MODULE_NAME
ARG TABLE_NAME
ARG SCHEMA_NAME


#### gencode-stage
COPY ./${SCHEMA_NAME} /$SCHEMA_NAME
WORKDIR /usr/src
RUN bash /usr/local/bin/gencode.sh ${MODULE_NAME} /$SCHEMA_NAME ${TABLE_NAME}

## workaround for resource
#add schema.sql into resource for initialize
COPY ./${SCHEMA_NAME} ./${MODULE_NAME}/src/main/resources/sql
## end 

## end gencode