version: '3.4'
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    image: crud_sandbox_api_cg  # temp name only for schema.sql
    container_name: crud_sandbox_api_cg
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SCHEMA_SQL: ./cg-mysql-schema.sql
        MODULE_NAME: cg
        SCHEMA_DESC: ./one.crud.json
    ports: # or nginx
      - 8080:8080
      
#default
networks:
  default:
    name: crud_sandbox_network
