version: '3.4'
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  api:
    image: crud_sandbox_api_cg  # temp name only for schema.sql
    container_name: crud_sandbox_api_cg
    build:
      context: ../   #for schemq.sql
      dockerfile: ./api/Dockerfile.cg
      args:
        SCHEMA_SQL: ./cg-mysql-schema.sql
        MODULE_NAME: cg
        SCHEMA_DESC: ./one.crud.json
        
#default
networks:
  default:
    name: crud_sandbox_network
