### 示例
GET https://example.com/topics/1 HTTP/1.1

@endpoint = http://localhost:8080
# @endpoint = http://192.168.3.239:8180

### 查询列表
GET {{endpoint}}/api/crud/masterResource/masterResources HTTP/1.1
content-type: application/json
origin: http://localhost:8180