version: '3.4'
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
# docker-compose run --rm zerocodegenerator cg /cg-mysql-schema.sql cg_master_resource
services:
  web:
    image: crud_sandbox_web_0  # temp name only for schema.sql
    container_name: crud_sandbox_web_0
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SCHEMA_SQL: ./cg-mysql-schema.sql
        TABLE_NAME: cg_master_resource
    volumes: 
      - ./config/global.js:/usr/src/web/src/global.js
      - ./config/config.js:/usr/src/web/public/config.js
    #for node-gateway below
      - ./out/web/src/pages:/usr/src/web/src/pages
    # just run 
    ports: 
      - 8001:8000
    command: 
        - npm
        - start
        
networks:
  default:
    name: crud_sandbox_network
